In [12]:
import os
import pandas as pd
import datetime

In [13]:
pwd = os.getcwd()

Import CSV file and save it as a dataframe

In [14]:
filepath = pwd +  "\COVID-19_Vaccinations_in_the_United_States_Jurisdiction.csv"
Vaccine_Daily = pd.read_csv(filepath)
Vaccine_Daily

C:\Users\cuban\miniconda3\lib\site-packages\IPython\core\interactiveshell.py:3457: DtypeWarning: Columns (4,5,6,7,9,10,11,13,14,15,16,21,22,23,24,25,27,29,31,33,35,37,39,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,59,61,63,65,66,67,68,69,71,73,74,75,76,77,78,79) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,Distributed_Per_100k_12Plus,...,Administered_Dose1_Recip_5PlusPop_Pct,Series_Complete_5Plus,Series_Complete_5PlusPop_Pct,Administered_5Plus,Admin_Per_100k_5Plus,Distributed_Per_100k_5Plus,Series_Complete_Moderna_5Plus,Series_Complete_Pfizer_5Plus,Series_Complete_Janssen_5Plus,Series_Complete_Unk_Manuf_5Plus
0,02/01/2022,5,OK,"6,764,610","321,200","2,766,460","3,676,950",0,"170,954","203,433",...,74.0,"2,183,755",59.0,"5,608,582","151,524","182,756","832,874","1,210,200","140,452",229
1,02/01/2022,5,TN,"11,814,170","500,500","4,410,780","6,902,890",0,"172,996","202,451",...,64.5,"3,604,842",56.1,"9,349,899","145,624","184,005","1,289,162","2,074,131","230,533","11,016"
2,02/01/2022,5,NY,"42,348,135","1,837,000","14,719,060","25,792,075",0,"217,688","252,475",...,93.0,"14,430,305",78.7,"36,741,826","200,484","231,075","4,880,309","8,313,743","1,231,437","4,816"
3,02/01/2022,5,ME,"3,098,950","151,700","1,207,320","1,739,930",0,"230,540","261,529",...,93.0,"1,042,528",81.4,"2,658,151","207,559","241,978","376,236","534,991","130,598",703
4,02/01/2022,5,TX,"56,859,835","2,586,700","20,177,120","34,096,015",0,"196,096","235,922",...,74.9,"17,083,597",63.3,"43,169,386","159,857","210,553","5,964,628","9,807,671","1,310,506",792
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26835,12/13/2020,51,LTC,0,0,0,0,0,0,0,...,0.0,0,0.0,0,0,0,NaN,NaN,NaN,NaN
26836,12/13/2020,51,AS,"3,900",0,0,0,0,"7,003",0,...,0.0,0,0.0,0,0,0,NaN,NaN,NaN,NaN
26837,12/13/2020,51,MP,"4,875",0,0,0,0,"8,570",0,...,0.0,0,0.0,0,0,0,NaN,NaN,NaN,NaN
26838,12/13/2020,51,US,"13,650",0,0,0,0,4,0,...,0.0,0,0.0,0,0,0,NaN,NaN,NaN,NaN
26839,12/13/2020,51,GU,"3,900",0,0,0,0,"2,353",0,...,0.0,0,0.0,0,0,0,NaN,NaN,NaN,NaN

Change Dataframe to only contain the states that will be compared

In [15]:


Comp_States = ["MA","MD","CT","VT","CO","VA","NJ","NH","MN","WA","AL","AK","LA","MS","WV","NM","SC","NV","OK","KY"]

Vaccine_Daily = Vaccine_Daily[Vaccine_Daily["Location"].isin(Comp_States)]
Vaccine_Daily

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,Distributed_Per_100k_12Plus,...,Administered_Dose1_Recip_5PlusPop_Pct,Series_Complete_5Plus,Series_Complete_5PlusPop_Pct,Administered_5Plus,Admin_Per_100k_5Plus,Distributed_Per_100k_5Plus,Series_Complete_Moderna_5Plus,Series_Complete_Pfizer_5Plus,Series_Complete_Janssen_5Plus,Series_Complete_Unk_Manuf_5Plus
0,02/01/2022,5,OK,"6,764,610","321,200","2,766,460","3,676,950",0,"170,954","203,433",...,74.0,"2,183,755",59.0,"5,608,582","151,524","182,756","832,874","1,210,200","140,452",229
6,02/01/2022,5,WA,"16,266,705","737,800","5,817,920","9,710,985",0,"213,617","250,221",...,83.8,"5,334,115",74.5,"13,436,387","187,701","227,239","1,859,521","3,027,132","443,931","3,531"
8,02/01/2022,5,AL,"8,903,600","394,100","3,780,120","4,729,380",0,"181,588","212,655",...,65.1,"2,426,346",52.6,"5,964,201","129,408","193,186","1,008,354","1,255,160","162,210",622
9,02/01/2022,5,MA,"15,680,650","605,400","5,876,560","9,198,690",0,"227,503","260,617",...,95.0,"5,270,420",80.6,"13,941,912","213,338","239,944","1,862,887","3,030,022","377,316",195
14,02/01/2022,5,CT,"8,024,515","336,700","3,035,340","4,652,475",0,"225,073","258,360",...,95.0,"2,731,116",80.7,"7,107,093","210,047","237,161","928,877","1,574,202","227,596",441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26816,12/14/2020,51,VA,"18,525",0,0,0,0,217,0,...,0.0,0,0.0,0,0,0,NaN,NaN,NaN,NaN
26817,12/14/2020,51,MS,"4,875",0,0,0,0,164,0,...,0.0,0,0.0,0,0,0,NaN,NaN,NaN,NaN
26818,12/14/2020,51,NV,"13,650",0,0,0,0,443,0,...,0.0,0,0.0,0,0,0,NaN,NaN,NaN,NaN
26819,12/14/2020,51,LA,"2,925",0,0,0,0,63,0,...,0.0,0,0.0,0,0,0,NaN,NaN,NaN,NaN
26825,12/14/2020,51,WV,"10,725",0,0,0,0,598,0,...,0.0,0,0.0,0,0,0,NaN,NaN,NaN,NaN

Seperating dates to better sort data

In [16]:
Vaccine_Daily[["Month","Day","Year"]] = Vaccine_Daily["Date"].str.split("/",expand = True)
Vaccine_Daily

C:\Users\cuban\miniconda3\lib\site-packages\pandas\core\frame.py:3641: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[k1] = value[k2]

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,Distributed_Per_100k_12Plus,...,Administered_5Plus,Admin_Per_100k_5Plus,Distributed_Per_100k_5Plus,Series_Complete_Moderna_5Plus,Series_Complete_Pfizer_5Plus,Series_Complete_Janssen_5Plus,Series_Complete_Unk_Manuf_5Plus,Month,Day,Year
0,02/01/2022,5,OK,"6,764,610","321,200","2,766,460","3,676,950",0,"170,954","203,433",...,"5,608,582","151,524","182,756","832,874","1,210,200","140,452",229,02,01,2022
6,02/01/2022,5,WA,"16,266,705","737,800","5,817,920","9,710,985",0,"213,617","250,221",...,"13,436,387","187,701","227,239","1,859,521","3,027,132","443,931","3,531",02,01,2022
8,02/01/2022,5,AL,"8,903,600","394,100","3,780,120","4,729,380",0,"181,588","212,655",...,"5,964,201","129,408","193,186","1,008,354","1,255,160","162,210",622,02,01,2022
9,02/01/2022,5,MA,"15,680,650","605,400","5,876,560","9,198,690",0,"227,503","260,617",...,"13,941,912","213,338","239,944","1,862,887","3,030,022","377,316",195,02,01,2022
14,02/01/2022,5,CT,"8,024,515","336,700","3,035,340","4,652,475",0,"225,073","258,360",...,"7,107,093","210,047","237,161","928,877","1,574,202","227,596",441,02,01,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26816,12/14/2020,51,VA,"18,525",0,0,0,0,217,0,...,0,0,0,NaN,NaN,NaN,NaN,12,14,2020
26817,12/14/2020,51,MS,"4,875",0,0,0,0,164,0,...,0,0,0,NaN,NaN,NaN,NaN,12,14,2020
26818,12/14/2020,51,NV,"13,650",0,0,0,0,443,0,...,0,0,0,NaN,NaN,NaN,NaN,12,14,2020
26819,12/14/2020,51,LA,"2,925",0,0,0,0,63,0,...,0,0,0,NaN,NaN,NaN,NaN,12,14,2020
26825,12/14/2020,51,WV,"10,725",0,0,0,0,598,0,...,0,0,0,NaN,NaN,NaN,NaN,12,14,2020

Sort Values by Location and then by year... I do it this way because the Date format was causing issues with the changes in the year which was messing with the Data frame presentation and ultimately the visuals themselves.

In [17]:
Vaccine_Daily_sorted = Vaccine_Daily.sort_values(["Location", "Year", "Day","Month"], ascending= True)
Vaccine_Daily_sorted

,Date,MMWR_week,Location,Distributed,Distributed_Janssen,Distributed_Moderna,Distributed_Pfizer,Distributed_Unk_Manuf,Dist_Per_100K,Distributed_Per_100k_12Plus,...,Administered_5Plus,Admin_Per_100k_5Plus,Distributed_Per_100k_5Plus,Series_Complete_Moderna_5Plus,Series_Complete_Pfizer_5Plus,Series_Complete_Janssen_5Plus,Series_Complete_Unk_Manuf_5Plus,Month,Day,Year
26800,12/14/2020,51,AK,"4,875",0,0,0,0,666,0,...,0,0,0,NaN,NaN,NaN,NaN,12,14,2020
26771,12/15/2020,51,AK,"12,675",0,0,0,0,"1,733",0,...,0,0,0,NaN,NaN,NaN,NaN,12,15,2020
26666,12/16/2020,51,AK,"26,325",0,0,0,0,"3,599",0,...,0,0,0,NaN,NaN,NaN,NaN,12,16,2020
26633,12/17/2020,51,AK,"26,325",0,0,0,0,"3,599",0,...,0,0,0,NaN,NaN,NaN,NaN,12,17,2020
26536,12/18/2020,51,AK,"26,325",0,0,0,0,"3,599",0,...,0,0,0,NaN,NaN,NaN,NaN,12,18,2020
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
322,01/27/2022,4,WV,"3,714,225","158,700","1,454,100","2,101,425",0,"207,250","238,422",...,"2,582,817","152,009","218,597","414,293","530,113","59,775",458,01,27,2022
313,01/28/2022,4,WV,"3,724,425","158,700","1,457,800","2,107,925",0,"207,819","239,077",...,"2,585,795","152,184","219,197","414,424","530,589","59,818",459,01,28,2022
201,01/29/2022,4,WV,"3,729,625","158,700","1,457,800","2,113,125",0,"208,109","239,410",...,"2,588,521","152,345","219,503","414,564","531,019","59,856",459,01,29,2022
179,01/30/2022,5,WV,"3,729,625","158,700","1,457,800","2,113,125",0,"208,109","239,410",...,"2,588,583","152,348","219,503","414,583","531,064","59,860",459,01,30,2022
64,01/31/2022,5,WV,"3,729,625","158,700","1,457,800","2,113,125",0,"208,109","239,410",...,"2,588,583","152,348","219,503","414,589","531,091","59,865",459,01,31,2022

Export Dataframe to do some exploratory data analysis in R, Excel, and PowerBI

In [18]:
#Vaccine_Daily_sorted.to_csv("Sorted_Vaccine_Data.csv",index = False)

Group the data into the top 10 and bottom 10 states by education.

In [19]:
Vaccine_Daily_sorted.groupby.get_group("Top Ten", )

AttributeError: 'Series' object has no attribute 'get_group'